name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - master

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker image build -t gabrielrufino/users-api:latest -t gabrielrufino/users-api:$(npm pkg get version | sed 's/"//g') .
      - run: docker login -u gabrielrufino -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - run: docker image push -a gabrielrufino/users-api
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: gabrielrufino
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: gabrielrufino/users-api
