name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }} # Remove
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }} # Remove
  dockerfile-ci:
    name: Dockerfile CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/dockerfile-ci@v2
